'use strict'
const StrategyType = {
  AAVE: 'aave',
  AAVE_V1: 'aaveV1',
  AAVE_V3: 'aaveV3',
  COMPOUND: 'compound',
  TRADER_JOE: 'traderJoe',
  AAVE_MAKER: 'aaveMaker',
  COMPOUND_MAKER: 'compoundMaker',
  VESPER_MAKER: 'vesperMaker',

  CURVE: 'curve',
  CONVEX: 'curveConvex',
  CONVEX_FOR_FRAX: 'fraxConvex',
  YEARN: 'yearn',
  YEARN_STAKING: 'yearnStaking',
  RARI_FUSE: 'rariFuse',
  COMPOUND_XY: 'compoundXY',
  COMPOUND_LEVERAGE: 'compoundLeverage',
  VESPER: 'vesper',
  COMPOUND_VESPER_XY: 'compoundVesperXY',
  AAVE_LEVERAGE: 'aaveLeverage',
  AAVE_VESPER_XY: 'aaveVesperXY',
  STARGATE: 'stargate',
  COMPOUNDV3: 'compoundV3',
  COMPOUNDV3_VESPER_XY: 'compoundV3VesperXY',
  AAVE_V3_VESPER_XY: 'aaveV3VesperXy',
  AAVE_V3_SOMMELIER_XY: 'aaveV3SommelierXy',
  ALPACA: 'alpaca',
  FRAX_LEND: 'fraxLend',
  FRAX_LEND_VESPER_XY: 'fraxLendVesperXY',
  SOMMELIER: 'sommelier',
  MORPHO: 'morpho',
  EXTRA_FINANCE: 'extraFinance',
  DUMMY: 'dummy',
}

module.exports = Object.freeze(StrategyType)
