'use strict'
const StrategyType = {
  AAVE: 'aave',
  AAVE_V1: 'aaveV1',
  COMPOUND: 'compound',
  TRADER_JOE: 'traderJoe',
  AAVE_MAKER: 'aaveMaker',
  COMPOUND_MAKER: 'compoundMaker',
  VESPER_MAKER: 'vesperMaker',
  EARN_VESPER_MAKER: 'earnVesperMaker',
  CURVE: 'curve',
  CONVEX: 'curveConvex',
  CONVEX_FOR_FRAX: 'fraxConvex',
  YEARN: 'yearn',
  YEARN_STAKING: 'yearnStaking',
  EARN_MAKER: 'earnMaker',
  EARN_COMPOUND: 'earnCompound',
  EARN_AAVE: 'earnAave',
  EARN_RARI_FUSE: 'earnRariFuse',
  EARN_YEARN: 'earnYearn',
  EARN_CURVE: 'earnCurve',
  EARN_VESPER: 'earnVesper',
  RARI_FUSE: 'rariFuse',
  COMPOUND_XY: 'compoundXY',
  COMPOUND_LEVERAGE: 'compoundLeverage',
  VESPER: 'vesper',
  COMPOUND_VESPER_XY: 'compoundVesperXY',
  AAVE_LEVERAGE: 'aaveLeverage',
  AAVE_VESPER_XY: 'aaveVesperXY',
  STARGATE: 'stargate',
  EULER: 'euler',
  EULER_VESPER_XY: 'eulerVesperXY',
  COMPOUNDV3: 'compoundV3',
  COMPOUNDV3_VESPER_XY: 'compoundV3VesperXY',
  AAVE_V3_VESPER_XY: 'aaveV3VesperXy',
  ELLIPSIS: 'ellipsis',
  DOT_DOT: 'dotDot',
  WOMBAT: 'wombat',
  ALPACA: 'alpaca',
  FRAX_LEND: 'fraxLend',
  FRAX_LEND_VESPER_XY: 'fraxLendVesperXY',
}

module.exports = Object.freeze(StrategyType)
