name: Base Morpho Vault Strategy
on:
  pull_request:
    paths:
      - ".github/workflows/base-morpho-vault.yml"
      - ".github/actions/setup-env/action.yml"
      - "vesper-commons/test/utils/setup.js"
      - "vesper-pools/contracts/pool/**/*.sol"
      - "vesper-pools/contracts/pool/*.sol"
      - "vesper-strategies/contracts/strategies/Strategy.sol"
      - "vesper-strategies/contracts/strategies/morpho/MorphoVault*"
      - "vesper-strategies/test/base/morpho/vault/*.js"

# Limit concurrency to one workflow per branch and one per pull_request
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-${{ github.event_name }}
  cancel-in-progress: true

jobs:
  setup-job:
    runs-on: ubuntu-latest
    env:
      NODE_URL: ${{ secrets.BASE_NODE_URL }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup env
        uses: ./.github/actions/setup-env

  vaeth-morpho-vault-test:
    needs: [setup-job]
    runs-on: ubuntu-latest
    env:
      NODE_URL: ${{ secrets.BASE_NODE_URL }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup env
        uses: ./.github/actions/setup-env

      - name: Running Morpho vault strategy for vaeth pool
        run: npm test -- --scope vesper-strategies -- test/base/morpho/vault/vaeth.spec.js

  vausdc-morpho-vault-test:
    needs: [setup-job]
    runs-on: ubuntu-latest
    env:
      NODE_URL: ${{ secrets.BASE_NODE_URL }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup env
        uses: ./.github/actions/setup-env

      - name: Running Morpho USDC vault strategy for vaUSDC pool
        run: npm test -- --scope vesper-strategies -- test/base/morpho/vault/vausdc.spec.js

  vamseth-vault-test:
    needs: [setup-job]
    runs-on: ubuntu-latest
    env:
      NODE_URL: ${{ secrets.BASE_NODE_URL }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup env
        uses: ./.github/actions/setup-env

      - name: Running Morpho msETH vault strategy for vamsETH pool
        run: npm test -- --scope vesper-strategies -- test/base/morpho/vault/vamseth.spec.js
